/**
 * Approval model for council dispatch (MCP-spec-compliant consent).
 *
 * Read-only from the MCP tool surface. The LLM cannot grant, revoke, or reset
 * approval. State is set out-of-band:
 *
 *   1. `FLYWHEEL_IDEAS_APPROVE` env var (`always` | `session` | `never`).
 *      Set when launching the MCP server. Takes precedence over the file.
 *   2. `<vaultPath>/.flywheel/ideas-approvals.json` (manually edited by user
 *      or written by a future admin CLI). Scope must be `always` or `never`.
 *
 * Rationale: MCP tool arguments are generated by the model. Putting consent
 * mutation behind a tool argument means any sufficiently-eager LLM can
 * self-grant. Keeping mutation out-of-band — env var or filesystem — makes
 * the user the only principal who can change the consent state.
 *
 * `grantApprovalFile` / `revokeApprovalFile` are exported for tests and a
 * future admin CLI. They MUST NOT be called from an MCP tool handler.
 */

import * as fsp from 'node:fs/promises';
import * as path from 'node:path';
import { randomBytes } from 'node:crypto';
import { FLYWHEEL_DIR } from './schema.js';

export type ApprovalScope = 'session' | 'always';
export type ApprovalFeature = 'council_dispatch';
export type EnvApprovalValue = 'always' | 'session' | 'never';

const APPROVAL_ENV_VAR = 'FLYWHEEL_IDEAS_APPROVE';
const APPROVALS_FILENAME = 'ideas-approvals.json';
const APPROVALS_SCHEMA_VERSION = 1;
const DEFAULT_BINARIES = ['claude', 'codex', 'gemini'] as const;

export interface PersistedApproval {
  feature: ApprovalFeature;
  scope: 'always' | 'never';
  granted_at: number;
  binaries: string[];
}

interface PersistedApprovalsFile {
  schema: number;
  approvals: PersistedApproval[];
}

export type ApprovalState =
  | {
      granted: true;
      scope: ApprovalScope;
      source: 'env' | 'persistent';
      granted_at: number;
      binaries: string[];
    }
  | { granted: false; reason: 'no_approval' | 'never_persisted' | 'never_env' };

export interface ApprovalStatusPayload {
  granted: boolean;
  scope?: ApprovalScope;
  source?: 'env' | 'persistent';
  granted_at?: number;
  binaries?: string[];
  reason?: 'no_approval' | 'never_persisted' | 'never_env';
  env_var: string;
  approvals_file: string;
}

/** Absolute path to the approvals file for a given vault. */
export function approvalsFilePath(vaultPath: string): string {
  return path.join(vaultPath, FLYWHEEL_DIR, APPROVALS_FILENAME);
}

function readEnvApproval(): EnvApprovalValue | null {
  const raw = process.env[APPROVAL_ENV_VAR];
  if (!raw) return null;
  const v = raw.trim().toLowerCase();
  if (v === 'always' || v === 'session' || v === 'never') return v;
  // Unknown value — ignore, fall through to file check. Log once to stderr.
  // (stderr is safe — MCP uses stdout only for JSON-RPC.)
  if (!envWarningEmitted.has(v)) {
    envWarningEmitted.add(v);
    process.stderr.write(
      `[flywheel-ideas] ignoring unrecognized ${APPROVAL_ENV_VAR}="${raw}"; expected always|session|never\n`,
    );
  }
  return null;
}
const envWarningEmitted = new Set<string>();

/**
 * Read the persistent approvals file, if any.
 *
 * - File missing → null (callers treat as "no approval")
 * - Malformed JSON → null + single stderr warning (don't crash)
 * - Wrong schema version → null + warning
 * - Missing `council_dispatch` entry → null
 */
export async function readPersistedApproval(
  vaultPath: string,
  feature: ApprovalFeature = 'council_dispatch',
): Promise<PersistedApproval | null> {
  const file = approvalsFilePath(vaultPath);
  let raw: string;
  try {
    raw = await fsp.readFile(file, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    emitFileWarning(file, `read failed: ${(err as Error).message}`);
    return null;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    emitFileWarning(file, 'malformed JSON — ignoring');
    return null;
  }

  if (!isPersistedApprovalsFile(parsed)) {
    emitFileWarning(file, 'schema mismatch — ignoring');
    return null;
  }

  const match = parsed.approvals.find((a) => a.feature === feature);
  return match ?? null;
}

const fileWarningEmitted = new Set<string>();
function emitFileWarning(file: string, detail: string): void {
  const key = `${file}:${detail}`;
  if (fileWarningEmitted.has(key)) return;
  fileWarningEmitted.add(key);
  process.stderr.write(`[flywheel-ideas] approvals file ${file}: ${detail}\n`);
}

function isPersistedApprovalsFile(x: unknown): x is PersistedApprovalsFile {
  if (typeof x !== 'object' || x === null) return false;
  const o = x as Record<string, unknown>;
  if (o.schema !== APPROVALS_SCHEMA_VERSION) return false;
  if (!Array.isArray(o.approvals)) return false;
  return o.approvals.every(isPersistedApproval);
}

function isPersistedApproval(x: unknown): x is PersistedApproval {
  if (typeof x !== 'object' || x === null) return false;
  const o = x as Record<string, unknown>;
  return (
    o.feature === 'council_dispatch' &&
    (o.scope === 'always' || o.scope === 'never') &&
    typeof o.granted_at === 'number' &&
    Array.isArray(o.binaries) &&
    o.binaries.every((b) => typeof b === 'string')
  );
}

/**
 * Resolve the current approval state for a feature.
 *
 * Precedence:
 *   1. env var `FLYWHEEL_IDEAS_APPROVE=never` → blocked
 *   2. env var `FLYWHEEL_IDEAS_APPROVE=always|session` → granted (source=env)
 *   3. persistent file says `never` → blocked
 *   4. persistent file says `always` → granted (source=persistent)
 *   5. otherwise → no approval
 */
export async function resolveApproval(
  vaultPath: string,
  feature: ApprovalFeature = 'council_dispatch',
): Promise<ApprovalState> {
  const env = readEnvApproval();
  if (env === 'never') {
    return { granted: false, reason: 'never_env' };
  }
  if (env === 'always' || env === 'session') {
    return {
      granted: true,
      scope: env,
      source: 'env',
      granted_at: Date.now(),
      binaries: [...DEFAULT_BINARIES],
    };
  }

  const persisted = await readPersistedApproval(vaultPath, feature);
  if (persisted?.scope === 'never') {
    return { granted: false, reason: 'never_persisted' };
  }
  if (persisted?.scope === 'always') {
    return {
      granted: true,
      scope: 'always',
      source: 'persistent',
      granted_at: persisted.granted_at,
      binaries: persisted.binaries,
    };
  }

  return { granted: false, reason: 'no_approval' };
}

/**
 * Shape an `ApprovalState` for an MCP tool response.
 *
 * Always includes `env_var` + `approvals_file` so the caller sees where to
 * grant/revoke out-of-band.
 */
export function approvalStatusForResponse(
  vaultPath: string,
  state: ApprovalState,
): ApprovalStatusPayload {
  const base = {
    env_var: APPROVAL_ENV_VAR,
    approvals_file: approvalsFilePath(vaultPath),
  };
  if (state.granted) {
    return {
      ...base,
      granted: true,
      scope: state.scope,
      source: state.source,
      granted_at: state.granted_at,
      binaries: state.binaries,
    };
  }
  return {
    ...base,
    granted: false,
    reason: state.reason,
  };
}

/**
 * Write a persistent approval. NOT called from any MCP handler. Exposed for
 * tests and a future admin CLI.
 *
 * Atomic: writes to a tmp file with a crypto-random suffix, then renames.
 * `.flywheel/` directory is auto-created if missing.
 */
export async function grantApprovalFile(
  vaultPath: string,
  scope: 'always' | 'never',
  options: {
    feature?: ApprovalFeature;
    binaries?: string[];
    granted_at?: number;
  } = {},
): Promise<PersistedApproval> {
  const feature = options.feature ?? 'council_dispatch';
  const binaries = options.binaries ?? [...DEFAULT_BINARIES];
  const granted_at = options.granted_at ?? Date.now();

  const file = approvalsFilePath(vaultPath);
  await fsp.mkdir(path.dirname(file), { recursive: true });

  const existing = await readApprovalsFileOrEmpty(file);
  const next: PersistedApproval = { feature, scope, granted_at, binaries };
  const others = existing.approvals.filter((a) => a.feature !== feature);
  const updated: PersistedApprovalsFile = {
    schema: APPROVALS_SCHEMA_VERSION,
    approvals: [...others, next],
  };

  const tmp = `${file}.${randomBytes(8).toString('hex')}.tmp`;
  await fsp.writeFile(tmp, JSON.stringify(updated, null, 2), 'utf8');
  await fsp.rename(tmp, file);
  return next;
}

/**
 * Remove the persistent approval for a feature. Out-of-band only — NOT
 * called from any MCP handler.
 *
 * If the feature isn't present, the call is a no-op. If removing it leaves
 * the file empty, the file is deleted.
 */
export async function revokeApprovalFile(
  vaultPath: string,
  feature: ApprovalFeature = 'council_dispatch',
): Promise<boolean> {
  const file = approvalsFilePath(vaultPath);
  const existing = await readApprovalsFileOrEmpty(file);
  const remaining = existing.approvals.filter((a) => a.feature !== feature);
  if (remaining.length === existing.approvals.length) return false;

  if (remaining.length === 0) {
    await fsp.unlink(file).catch(() => {
      /* already gone */
    });
    return true;
  }

  const updated: PersistedApprovalsFile = {
    schema: APPROVALS_SCHEMA_VERSION,
    approvals: remaining,
  };
  const tmp = `${file}.${randomBytes(8).toString('hex')}.tmp`;
  await fsp.writeFile(tmp, JSON.stringify(updated, null, 2), 'utf8');
  await fsp.rename(tmp, file);
  return true;
}

async function readApprovalsFileOrEmpty(file: string): Promise<PersistedApprovalsFile> {
  try {
    const raw = await fsp.readFile(file, 'utf8');
    const parsed = JSON.parse(raw);
    if (isPersistedApprovalsFile(parsed)) return parsed;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      // Corrupt file — overwrite with a clean one.
    }
  }
  return { schema: APPROVALS_SCHEMA_VERSION, approvals: [] };
}
