/**
 * Render a portfolio export as human-readable markdown.
 *
 * This is the product. The markdown is what an operator hands to a colleague
 * to ask for feedback on a decision; everything else (JSON, schema versions,
 * vault paths) is plumbing.
 *
 * Design choices:
 * - Stable section ordering. Reader scrolls predictably across exports.
 * - Redaction posture: `redact_bodies: true` hides idea bodies; assumptions /
 *   outcomes / council excerpts always render (those are the load-bearing
 *   content). Footer makes the redaction state explicit.
 * - Council excerpts cap at ~800 chars per session to avoid swamping the
 *   reader; full SYNTHESIS.md is referenced by relative path.
 * - Tables for assumptions (3-column: id, status, text) — scannable.
 * - Outcomes as a chronological list with verdict badges.
 * - Lineage as inline lists (ancestors above the idea, descendants below).
 *
 * The renderer never throws on absent data — missing body / missing council
 * synthesis / no outcomes / no lineage all degrade to a clear notice.
 */

import { createHash } from 'node:crypto';
import type {
  ExportPortfolio,
  ExportedIdea,
  ExportedOutcome,
  ExportedCouncilSession,
  ExportedLineage,
} from './export.js';

export interface RenderPortfolioOptions {
  /** Hide idea bodies in the rendered output. Default true (paranoid default). */
  redact_bodies?: boolean;
  /** Optional human-readable title for the bundle (e.g. "PEP 3000 portfolio"). */
  title?: string;
}

const SYNTHESIS_EXCERPT_CHARS = 800;

const STATE_BADGE: Record<string, string> = {
  nascent: '🌱',
  explored: '🔎',
  evaluated: '⚖️',
  committed: '✅',
  validated: '🟢',
  parked: '⏸',
  killed: '🚫',
  refuted: '🔴',
};

/**
 * Render a portfolio export as markdown.
 */
export function renderPortfolioMarkdown(
  portfolio: ExportPortfolio,
  options: RenderPortfolioOptions = {},
): string {
  const redact_bodies = options.redact_bodies ?? true;
  const title = options.title ?? defaultTitle(portfolio);

  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push('');
  lines.push(
    `*Generated by [flywheel-ideas](https://github.com/velvetmonkey/flywheel-ideas) on ${portfolio.exported_at_iso}. ` +
      `${portfolio.ideas.length} idea${portfolio.ideas.length === 1 ? '' : 's'}; ` +
      `bodies ${redact_bodies ? '**redacted**' : '**included**'}.*`,
  );
  lines.push('');
  lines.push(
    '> **About this document.** This is a *decision portfolio* exported from a flywheel-ideas vault. ' +
      'Each section captures one idea, its declared assumptions, the AI council\'s critique of those assumptions, ' +
      'and any outcomes that have landed since. The point is to make the reasoning behind a decision legible and falsifiable — ' +
      'when an assumption breaks, a future reader can see exactly which decision is now in question.',
  );
  lines.push('');

  for (const idea of portfolio.ideas) {
    lines.push(...renderIdea(idea, { redact_bodies }));
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Footer
  lines.push('## Footer');
  lines.push('');
  lines.push(`- Schema: \`flywheel-ideas-portfolio v${portfolio.schema_version}\``);
  lines.push(`- Vault path (sha256-truncated for anonymity): \`${anonymisedVaultRef(portfolio.vault_path)}\``);
  lines.push(`- Exported at: ${portfolio.exported_at_iso}`);
  lines.push(
    `- Bodies: ${redact_bodies ? '**redacted**. Re-run with `redact_bodies: false` to include idea body prose.' : '**included**. Be aware of personal / professional context before sharing externally.'}`,
  );
  lines.push('');

  return lines.join('\n');
}

function renderIdea(
  idea: ExportedIdea,
  options: { redact_bodies: boolean },
): string[] {
  const lines: string[] = [];
  const { snapshot } = idea;
  const badge = STATE_BADGE[snapshot.idea.state] ?? '•';

  lines.push(`## ${badge} ${snapshot.idea.title}`);
  lines.push('');

  // Metadata block
  lines.push(`- **Idea id:** \`${snapshot.idea.id}\``);
  lines.push(`- **State:** \`${snapshot.idea.state}\``);
  lines.push(`- **Frozen at:** ${snapshot.frozen_at_iso}${idea.freeze_id ? ` (freeze \`${idea.freeze_id}\`)` : ' (transient snapshot — no persisted freeze)'}`);
  if (idea.lineage) {
    lines.push(...renderLineageInline(idea.lineage));
  }
  lines.push('');

  if (snapshot.idea.context) {
    lines.push('### Private context');
    lines.push('');
    if (snapshot.idea.context.situational_context) {
      lines.push(`- **Situational context:** ${snapshot.idea.context.situational_context}`);
    }
    if (snapshot.idea.context.mental_or_physical_state) {
      lines.push(`- **Mental or physical state:** ${snapshot.idea.context.mental_or_physical_state}`);
    }
    if (snapshot.idea.context.expected_outcome) {
      lines.push(`- **Expected outcome:** ${snapshot.idea.context.expected_outcome}`);
    }
    if (snapshot.idea.context.review_date) {
      lines.push(`- **Review date:** ${snapshot.idea.context.review_date}`);
    }
    if (
      snapshot.idea.context.alternatives_considered &&
      snapshot.idea.context.alternatives_considered.length > 0
    ) {
      lines.push('- **Alternatives considered:**');
      for (const alternative of snapshot.idea.context.alternatives_considered) {
        lines.push(`  - ${alternative.title}: ${alternative.why_rejected}`);
      }
    }
    lines.push('');
  }

  // Body (or redaction notice)
  lines.push('### Body');
  lines.push('');
  if (options.redact_bodies) {
    lines.push('> _Body redacted by export (`redact_bodies: true`). Run with `redact_bodies: false` to include the idea\'s prose._');
  } else if (snapshot.idea.body.trim() === '') {
    lines.push('> _No body — the idea was created without prose, or the markdown file was missing at snapshot time._');
  } else {
    lines.push(snapshot.idea.body.trim());
  }
  lines.push('');

  // Assumptions
  lines.push('### Declared assumptions');
  lines.push('');
  if (snapshot.assumptions.length === 0) {
    lines.push('> _No assumptions declared at snapshot time._');
  } else {
    lines.push('| id | status | load-bearing | text |');
    lines.push('|---|---|---|---|');
    for (const a of snapshot.assumptions) {
      const lb = a.load_bearing ? '⭐' : '';
      const text = mdTableEscape(a.text);
      lines.push(`| \`${a.id}\` | \`${a.status}\` | ${lb} | ${text} |`);
    }
  }
  lines.push('');

  // Outcomes
  lines.push('### Outcomes');
  lines.push('');
  if (idea.outcomes.length === 0) {
    lines.push('> _No outcomes logged. The decision is still live — no reality has arrived yet._');
  } else {
    for (const o of idea.outcomes) {
      lines.push(...renderOutcome(o));
    }
  }
  lines.push('');

  // Council sessions
  lines.push('### Council sessions');
  lines.push('');
  if (idea.council_sessions.length === 0) {
    lines.push('> _No council sessions on record. The assumptions have not been stress-tested yet._');
  } else {
    for (const s of idea.council_sessions) {
      lines.push(...renderCouncilSession(s));
    }
  }
  lines.push('');

  return lines;
}

function renderLineageInline(lineage: ExportedLineage): string[] {
  const lines: string[] = [];
  if (lineage.ancestors.length === 0 && lineage.descendants.length === 0) {
    lines.push('- **Lineage:** none — this idea has no recorded supersession ancestors or descendants.');
    return lines;
  }
  if (lineage.ancestors.length > 0) {
    const items = lineage.ancestors
      .map((a) => `\`${a.id}\` *${a.title}* (\`${a.state}\`)`)
      .join(' → ');
    lines.push(`- **Supersedes:** ${items}`);
  }
  if (lineage.descendants.length > 0) {
    const items = lineage.descendants
      .map((d) => `\`${d.id}\` *${d.title}* (\`${d.state}\`)`)
      .join(' → ');
    lines.push(`- **Superseded by:** ${items}`);
  }
  return lines;
}

function renderOutcome(o: ExportedOutcome): string[] {
  const lines: string[] = [];
  const refutes = o.verdicts.filter((v) => v.verdict === 'refuted');
  const validates = o.verdicts.filter((v) => v.verdict === 'validated');

  lines.push(`#### ${o.landed_at_iso} — outcome \`${o.id}\``);
  lines.push('');
  lines.push(o.text.trim());
  lines.push('');
  if (refutes.length > 0) {
    lines.push('**Refutes:**');
    for (const v of refutes) {
      lines.push(`- 🔴 \`${v.assumption_id}\` — ${v.assumption_text}`);
    }
    lines.push('');
  }
  if (validates.length > 0) {
    lines.push('**Validates:**');
    for (const v of validates) {
      lines.push(`- 🟢 \`${v.assumption_id}\` — ${v.assumption_text}`);
    }
    lines.push('');
  }
  if (o.undone_at !== null) {
    lines.push(`> *Outcome undone at ${new Date(o.undone_at).toISOString()}.*`);
    lines.push('');
  }
  return lines;
}

function renderCouncilSession(s: ExportedCouncilSession): string[] {
  const lines: string[] = [];
  const completed = s.completed_at !== null
    ? new Date(s.completed_at).toISOString()
    : '_not completed_';
  lines.push(`#### ${s.started_at_iso} — \`${s.mode}\` (${s.depth}) · session \`${s.id}\``);
  lines.push('');
  lines.push(`- Mode: \`${s.mode}\` · Depth: \`${s.depth}\``);
  lines.push(`- Completed: ${completed}`);
  if (s.synthesis_missing || s.synthesis_md === null) {
    lines.push('- Synthesis: _missing — the SYNTHESIS.md file was not on disk when the export ran._');
  } else {
    const excerpt = excerpt800(s.synthesis_md);
    lines.push('- Synthesis excerpt:');
    lines.push('');
    lines.push('  > ' + excerpt.replace(/\n/g, '\n  > '));
    if (s.synthesis_md.length > SYNTHESIS_EXCERPT_CHARS && s.synthesis_vault_path) {
      lines.push('');
      lines.push(`  *Truncated. Full synthesis at \`${s.synthesis_vault_path}\` in the source vault.*`);
    }
  }
  lines.push('');
  return lines;
}

function defaultTitle(portfolio: ExportPortfolio): string {
  if (portfolio.ideas.length === 1) {
    return `Decision portfolio — ${portfolio.ideas[0].snapshot.idea.title}`;
  }
  return `Decision portfolio — ${portfolio.ideas.length} ideas`;
}

/**
 * SHA-256 hash of the vault path, truncated to 12 hex chars. Provides a stable
 * identifier for the source vault without leaking the absolute path.
 */
function anonymisedVaultRef(vaultPath: string): string {
  return createHash('sha256').update(vaultPath).digest('hex').slice(0, 12);
}

function mdTableEscape(text: string): string {
  // Pipe character breaks markdown tables; escape it. Newlines in table cells
  // get collapsed to spaces (markdown tables don't render multi-line cells).
  return text.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function excerpt800(md: string): string {
  // Strip leading YAML frontmatter (--- ... ---) so the excerpt starts on prose,
  // not metadata. Reader doesn't need to see session_id/idea_id/mode duplicated
  // from the metadata block we already render above.
  let body = md;
  const fmMatch = body.match(/^---\n[\s\S]*?\n---\n/);
  if (fmMatch) {
    body = body.slice(fmMatch[0].length);
  }
  body = body.trim();
  if (body.length <= SYNTHESIS_EXCERPT_CHARS) return body;
  return body.slice(0, SYNTHESIS_EXCERPT_CHARS).trim() + '…';
}
